import {
    Button,
    VerticalBox,
    HorizontalBox,
    Switch,
    TextEdit,
    LineEdit,
    ProgressIndicator,
} from "std-widgets.slint";

import { HeadersSettingDialog } from "dialogs/headers-setting-dialog.slint";
import { ResultDialog } from "dialogs/result-dialog.slint";
import { ErrorDialog } from "dialogs/error-dialog.slint";

import { RequestData } from "bindings/request-data.slint";
import { ControlsBinding } from "bindings/controls-binding.slint";

export {
    HeadersSettingDialog,
    ResultDialog,
    RequestData,
    ErrorDialog,
    ControlsBinding,
}
export component AppWindow inherits Window {
    title: "Mini API Controller";
    preferred-width: 550px;
    preferred-height: 250px;
    min-width: 420px;
    min-height: 240px;
    callback request-clicked(bool);
    callback headers-setting-clicked();
    property <string> edit-font-family: "Consolas";
    property <bool> is_post: false;

    VerticalLayout {
        HorizontalBox {
            Switch {
                text: is_post ? "POST" : "GET  ";
                checked <=> root.is_post;
            }

            LineEdit {
                placeholder-text: "https://www.example.com/api";
                text <=> RequestData.request-url;
                font-size: 16px;
                font-family: root.edit-font-family;
                vertical-stretch: 0;
            }

            Button {
                text: "HTTP Headers Setting";
                clicked => {
                    root.headers-setting-clicked();
                }
            }
        }

        VerticalBox {
            LineEdit {
                text <=> RequestData.request-ua;
                font-family: root.edit-font-family;
            }

            TextEdit {
                text <=> RequestData.request-content;
                font-family: root.edit-font-family;
            }

            ProgressIndicator {
                visible: ControlsBinding.is-loading;
                indeterminate: true;
            }

            Button {
                text: root.is_post ? "POST" : "GET";
                clicked => {
                    root.request-clicked(is_post);
                };
            }
        }
    }
}
