export global RequestData {
    in-out property <[[StandardListViewItem]]> request-headers: [[{ text: "Content-Type" }, { text: "json/application" }]];
    in-out property <string> request-url;
    in-out property <string> request-content: "{\"Content\":\"Hello\"}";
    in-out property <string> request-ua: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36";
}
